### ISSUE TITLE
现在还可以运行么？准备买房

### ISSUE THREAD

**Issue by RaiderYi** [yuanyeon/HousePriceAnalysis#1]
RT
谢谢

**Comment by HectorYuan** [comment]
这个项目我有一段时间没维护了，也没咋关注FTX的网站。
FTX应该已经改变了页面结构，不过稍微修改下bs相关代码应该还能用。
再者就是高德的api要用你自己的，我直接放的自己的token被搞挂了，你换成自己的应该也可以用
